server:
  port: 8089

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/activiti_db?autoReconnect=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

  activiti:
    check-process-definitions: false

mybatis:
  type-aliases-package: com.chace.activiti.demo.entity

